spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.100.112:3306/mysell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.100.112
eureka:
  client:
    service-url:
       defaultZone: http://192.168.100.117:8761/eureka
server:
  port: 8081
env: dev6
girl: 
  name: wang
  age: 15
#PRODUCT:
#  ribbon:
##    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
