spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.100.112:3306/mysell?characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.100.112
    port: 6379
server:
  port: 8009
